version: '3.8'

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v2.8.7
    container_name: 3x-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/3x-ui/db:/etc/x-ui
      - /opt/3x-ui/cert:/root/cert
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    tty: true
